#!/usr/bin/env python3
"""
Regenerate the autogenerated regions of wiki/map.md from note frontmatter, and
lint cross-references. Stdlib-only so it can run from a git pre-commit hook with
no environment setup.

Autogenerated (between <!-- autogen:* --> markers in map.md):
  - the concept registry table (alphabetical by title)
  - the Mermaid prerequisite graph (edges: prerequisite --> concept)

Curated regions of map.md (intro, learning tracks) are preserved untouched.

Convention: the FIRST key in a note's `sources:` is its derivation-primary
(marked with a filled triangle in the registry); the rest are secondary.

Lint (non-zero exit blocks a commit):
  - every [[wikilink]] target resolves to an existing note
  - every `requires:` slug resolves to an existing note
  - every `sources:` key exists in references.md

Diagnostics (warn-only; printed, never block a commit):
  - forward-references to planned (unwritten) notes, ranked by inbound count
    (the highest-inbound planned target is the highest-value next stub to write)
  - lateral cross-links lacking a reciprocal back-edge (candidate missing links
    on the conceptual axes); excludes prereq pairs — already encoded in the
    `requires:` DAG and rendered in the graph — and reference-grade hub notes
    (e.g. notation) that are linked one-way by convention

Usage:
  python3 scripts/build_index.py          # rewrite map.md autogen regions + lint
  python3 scripts/build_index.py --check   # lint + verify map.md is up to date; no write
  python3 scripts/build_index.py --links   # audit view: full reciprocity + forward-ref
                                           # diagnostics, no write
"""
import collections
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
MAP = WIKI / "map.md"
REFS = ROOT / "references.md"
REVIEWS = WIKI / "reviews"
GAPS = WIKI / "gaps.md"

# meta files that are not concept notes (excluded from the registry/graph)
NOT_CONCEPTS = {"CONVENTIONS.md", "map.md"}

PRIMARY_MARK = "&#9656;"  # ▸ filled right-pointing triangle (HTML entity = renderer-safe)

WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


# ----------------------------------------------------------------------------- parsing
def parse_frontmatter(text):
    """Return (frontmatter_dict, body_str) or (None, text) if no frontmatter."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return None, text
    close = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            close = i
            break
    if close is None:
        return None, text
    fm = {}
    for ln in lines[1:close]:
        if ":" not in ln:
            continue
        key, val = ln.split(":", 1)
        key, val = key.strip(), val.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            fm[key] = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        else:
            if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
                val = val[1:-1]
            fm[key] = val
    body = "\n".join(lines[close + 1:])
    return fm, body


def load_notes():
    notes = {}
    for path in sorted(WIKI.glob("*.md")):
        if path.name in NOT_CONCEPTS:
            continue
        fm, body = parse_frontmatter(path.read_text())
        if fm is None or "slug" not in fm:
            continue
        notes[fm["slug"]] = {"fm": fm, "body": body, "path": path}
    return notes


def load_ref_keys():
    keys = set()
    if not REFS.exists():
        return keys
    for ln in REFS.read_text().split("\n"):
        m = re.match(r"\|\s*`([^`]+)`\s*\|", ln)
        if m:
            keys.add(m.group(1))
    return keys


# ----------------------------------------------------------------------------- lint
def all_note_stems():
    return {p.stem for p in WIKI.glob("*.md")}


def link_target(raw):
    # strip display text and heading anchor: [[slug#sec|Display]] -> slug
    raw = raw.replace("\\|", "|")  # escaped pipe used inside markdown tables
    return raw.split("|", 1)[0].split("#", 1)[0].strip()


PLANNED_RE = re.compile(r"^\s*-\s+`([a-z0-9][a-z0-9-]*)`")


def load_planned():
    """Planned-but-unwritten concept slugs, read from map.md's 'Planned concepts'
    section (lines like '- `slug` — description'). Forward-links to these are
    legitimate, not broken."""
    if not MAP.exists():
        return set()
    planned, in_section = set(), False
    for ln in MAP.read_text().split("\n"):
        if ln.startswith("## "):
            in_section = "planned concept" in ln.lower()
            continue
        if in_section:
            m = PLANNED_RE.match(ln)
            if m:
                planned.add(m.group(1))
    return planned


def lint(notes, ref_keys, planned):
    errors, forward = [], []
    stems = all_note_stems() | {"map"}
    for slug, n in notes.items():
        name = n["path"].name
        full = n["path"].read_text()
        for raw in WIKILINK_RE.findall(full):
            tgt = link_target(raw)
            if not tgt or tgt in stems:
                continue
            if tgt in planned:
                forward.append((name, tgt))
            else:
                errors.append(f"{name}: broken wikilink [[{tgt}]]")
        for req in n["fm"].get("requires", []):
            if req not in notes and req not in planned:
                errors.append(f"{name}: requires unknown note '{req}'")
        for src in n["fm"].get("sources", []):
            if src not in ref_keys:
                errors.append(f"{name}: source key '{src}' missing from references.md")
    return errors, forward


# --------------------------------------------------------------------- diagnostics
def body_link_graph(notes):
    """slug -> set of body-wikilink targets that are existing notes (excludes
    self-links, map, and links to planned/unwritten slugs)."""
    links = {}
    for slug, n in notes.items():
        tgts = set()
        for raw in WIKILINK_RE.findall(n["path"].read_text()):
            tgt = link_target(raw)
            if tgt and tgt in notes and tgt != slug:
                tgts.add(tgt)
        links[slug] = tgts
    return links


def reciprocity_warnings(notes):
    """Lateral body-link asymmetries: A links to B but B has no link back to A.
    Returns a sorted list of (a, b) candidate missing back-edges.

    Two classes of asymmetry are correct by design and therefore skipped:
      - prereq pairs (A,B in a `requires:` relation, either direction) — that
        connection is already encoded in the DAG and rendered in the graph;
      - reference-grade hub notes (e.g. notation) at either endpoint — they are
        linked one-way by convention and should not be reciprocated.
    What remains are lateral conceptual links (the DP-spine, optimism, and
    information axes, etc.) where a missing back-edge is a real candidate gap."""
    links = body_link_graph(notes)
    reqs = {s: set(n["fm"].get("requires", [])) for s, n in notes.items()}
    hub = {s for s, n in notes.items() if n["fm"].get("grade") == "reference"}
    warnings = []
    for a in sorted(links):
        for b in sorted(links[a]):
            if a in hub or b in hub:
                continue
            if b in reqs.get(a, ()) or a in reqs.get(b, ()):
                continue
            if a not in links.get(b, set()):
                warnings.append((a, b))
    return warnings


def print_diagnostics(forward, recip, detail=False):
    """Warn-only diagnostics: forward-refs ranked by inbound count, and lateral
    cross-links missing a reciprocal back-edge. Never affects the exit code.

    Forward-refs print in full (short, high-value: names the next stub to write).
    The reciprocity list can be long, so it prints a one-line summary by default
    and the full enumeration only when `detail` is set (the --links flag)."""
    if forward:
        inbound = collections.Counter(tgt for _, tgt in forward)
        srcs = collections.defaultdict(list)
        for name, tgt in forward:
            srcs[tgt].append(name[:-3] if name.endswith(".md") else name)
        print(f"note: {len(forward)} forward-reference(s) to {len(inbound)} planned "
              "(unwritten) note(s), by inbound count (highest = best next stub):")
        for tgt, cnt in sorted(inbound.items(), key=lambda kv: (-kv[1], kv[0])):
            print(f"  - [[{tgt}]]  <- {cnt} ref(s): {', '.join(sorted(srcs[tgt]))}")
    if recip:
        if detail:
            print(f"note: {len(recip)} lateral cross-link(s) without a reciprocal "
                  "back-edge (candidate missing links; warn-only):")
            for a, b in recip:
                print(f"  - {a} -> {b}  (no [[{a}]] back-link in {b})")
        else:
            print(f"note: {len(recip)} lateral cross-link(s) lack a reciprocal "
                  "back-edge (candidate missing links) — run "
                  "`python3 scripts/build_index.py --links` to list")


# ----------------------------------------------------------------------------- render
def render_registry(notes):
    rows = []
    for slug in sorted(notes, key=lambda s: notes[s]["fm"].get("title", s).lower()):
        fm = notes[slug]["fm"]
        title = fm.get("title", slug)
        concept = f"[[{slug}\\|{title}]]"
        summary = fm.get("summary", "").replace("|", "\\|")
        tags = " · ".join(fm.get("tags", [])) or "—"
        reqs = fm.get("requires", [])
        requires = " · ".join(f"[[{r}]]" for r in reqs) or "—"
        srcs = fm.get("sources", [])
        src_cells = [(f"{s}{PRIMARY_MARK}" if i == 0 else s) for i, s in enumerate(srcs)]
        sources = " · ".join(src_cells) or "—"
        grade = fm.get("grade", "—")
        reviewed = fm.get("reviewed", "null")
        reviewed = "—" if reviewed in ("null", "", None) else f"{reviewed} ✓"
        rows.append(f"| {concept} | {summary} | {tags} | {requires} | {sources} | {grade} | {reviewed} |")
    header = (
        "| Concept | Summary | Tags | Requires | Sources (" + PRIMARY_MARK + "=derivation-primary) | Grade | Reviewed |\n"
        "|---------|---------|------|----------|--------------------------------|-------|----------|"
    )
    return header + "\n" + "\n".join(rows)


def render_graph(notes):
    lines = ["```mermaid", "graph TD"]
    for slug in sorted(notes):
        for req in notes[slug]["fm"].get("requires", []):
            if req in notes:
                lines.append(f"    {req} --> {slug}")
    # isolated nodes (no prereqs and not required by anyone) still get declared
    referenced = set()
    for slug in notes:
        for req in notes[slug]["fm"].get("requires", []):
            referenced.add(req)
            referenced.add(slug)
    for slug in sorted(notes):
        if slug not in referenced:
            lines.append(f"    {slug}")
    lines.append("```")
    return "\n".join(lines)


def splice(text, name, payload):
    start = f"<!-- autogen:{name}:start -->"
    end = f"<!-- autogen:{name}:end -->"
    if start not in text or end not in text:
        sys.exit(f"ERROR: map.md missing markers for '{name}' ({start} / {end})")
    pre = text.split(start)[0]
    post = text.split(end, 1)[1]
    return f"{pre}{start}\n{payload}\n{end}{post}"


# ----------------------------------------------------------------------------- gaps
FINDING_RE = re.compile(
    r"^\s*-\s*\[([^\]]+)\]\s+([A-Za-z][\w-]*)\s+\(([^)]+)\)\s*[\u2014-]\s*(.*\S)"
)
SEVERITY_ORDER = {"blocker": 0, "gap": 1, "nit": 2}


def load_open_gaps():
    """Walk wiki/reviews/*.md and collect findings still marked (open).
    Returns a list of (gap_id, slug, severity, text). Empty if no reviews/ dir."""
    gaps = []
    if not REVIEWS.exists():
        return gaps
    for path in sorted(REVIEWS.glob("*.md")):
        fm, body = parse_frontmatter(path.read_text())
        slug = (fm or {}).get("note", path.stem)
        for ln in body.split("\n"):
            m = FINDING_RE.match(ln)
            if not m:
                continue
            gap_id, severity, status, text = m.groups()
            if status.strip().lower() != "open":
                continue
            gaps.append((gap_id.strip(), slug, severity.strip().lower(), text.strip()))
    return gaps


def render_gaps(gaps):
    """Render the generated, open-only gaps board (wiki/gaps.md)."""
    header = (
        "<!-- generated by build_index.py from wiki/reviews/ \u2014 do not edit -->\n"
        "# Open gaps\n\n"
        "Concept gaps still open across the wiki, aggregated from per-note review logs "
        "(`wiki/reviews/`). Regenerate with `python3 scripts/build_index.py`.\n\n"
    )
    if not gaps:
        return header + "_No open gaps._\n"
    ordered = sorted(gaps, key=lambda g: (SEVERITY_ORDER.get(g[2], 9), g[1], g[0]))
    rows = ["| gap | note | description | severity |",
            "|-----|------|-------------|----------|"]
    for gap_id, slug, severity, text in ordered:
        if len(text) > 120:
            text = text[:119].rstrip() + "\u2026"
        text = text.replace("|", "\\|")
        rows.append(f"| {gap_id} | [[{slug}]] | {text} | {severity} |")
    return header + "\n".join(rows) + "\n"


# ----------------------------------------------------------------------------- main
def main():
    check = "--check" in sys.argv
    links = "--links" in sys.argv
    notes = load_notes()
    ref_keys = load_ref_keys()
    planned = load_planned()

    errors, forward = lint(notes, ref_keys, planned)
    if errors:
        print("LINT FAILED:", file=sys.stderr)
        for e in errors:
            print("  - " + e, file=sys.stderr)
        sys.exit(1)
    print_diagnostics(forward, reciprocity_warnings(notes), detail=links)
    if links:
        return  # --links is an audit view: full diagnostics, no map.md rewrite

    if not MAP.exists():
        sys.exit("ERROR: wiki/map.md does not exist (create it with autogen markers first)")

    original = MAP.read_text()
    updated = splice(original, "registry", render_registry(notes))
    updated = splice(updated, "graph", render_graph(notes))

    open_gaps = load_open_gaps()
    gaps_new = render_gaps(open_gaps) if REVIEWS.exists() else None
    gaps_old = GAPS.read_text() if GAPS.exists() else None
    gaps_stale = gaps_new is not None and gaps_new != gaps_old

    if check:
        stale = []
        if updated != original:
            stale.append("map.md")
        if gaps_stale:
            stale.append("gaps.md")
        if stale:
            sys.exit(" and ".join(stale) + " stale: run `python3 scripts/build_index.py` and commit the result")
        gaps_note = f", {len(open_gaps)} open gap(s)" if REVIEWS.exists() else ""
        print(f"OK: {len(notes)} notes{gaps_note}, index up to date, lint clean")
        return

    msgs = [f"map.md regenerated ({len(notes)} notes)" if updated != original
            else f"map.md already current ({len(notes)} notes)"]
    if updated != original:
        MAP.write_text(updated)
    if gaps_stale:
        GAPS.write_text(gaps_new)
        msgs.append(f"gaps.md regenerated ({len(open_gaps)} open)")
    print("; ".join(msgs) + "; lint clean")


if __name__ == "__main__":
    main()
