#!/usr/bin/env python3
"""
Regenerate the autogenerated regions of wiki/map.md from note frontmatter, and
lint cross-references. Stdlib-only so it can run from a git pre-commit hook with
no environment setup.

Autogenerated (between <!-- autogen:* --> markers in map.md):
  - the concept registry table (alphabetical by title)
  - the Mermaid prerequisite graph (edges: prerequisite --> concept)

Curated regions of map.md (intro, learning tracks) are preserved untouched.

Convention: the FIRST key in a note's `sources:` is its derivation-primary
(marked with a filled triangle in the registry); the rest are secondary.

Lint (non-zero exit blocks a commit):
  - every [[wikilink]] target resolves to an existing note
  - every `requires:` slug resolves to an existing note
  - every `sources:` key exists in references.md

Usage:
  python3 scripts/build_index.py          # rewrite map.md autogen regions + lint
  python3 scripts/build_index.py --check   # lint + verify map.md is up to date; no write
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
MAP = WIKI / "map.md"
REFS = ROOT / "references.md"

# meta files that are not concept notes (excluded from the registry/graph)
NOT_CONCEPTS = {"CONVENTIONS.md", "map.md"}

PRIMARY_MARK = "&#9656;"  # ▸ filled right-pointing triangle (HTML entity = renderer-safe)

WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


# ----------------------------------------------------------------------------- parsing
def parse_frontmatter(text):
    """Return (frontmatter_dict, body_str) or (None, text) if no frontmatter."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return None, text
    close = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            close = i
            break
    if close is None:
        return None, text
    fm = {}
    for ln in lines[1:close]:
        if ":" not in ln:
            continue
        key, val = ln.split(":", 1)
        key, val = key.strip(), val.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            fm[key] = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        else:
            if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
                val = val[1:-1]
            fm[key] = val
    body = "\n".join(lines[close + 1:])
    return fm, body


def load_notes():
    notes = {}
    for path in sorted(WIKI.glob("*.md")):
        if path.name in NOT_CONCEPTS:
            continue
        fm, body = parse_frontmatter(path.read_text())
        if fm is None or "slug" not in fm:
            continue
        notes[fm["slug"]] = {"fm": fm, "body": body, "path": path}
    return notes


def load_ref_keys():
    keys = set()
    if not REFS.exists():
        return keys
    for ln in REFS.read_text().split("\n"):
        m = re.match(r"\|\s*`([^`]+)`\s*\|", ln)
        if m:
            keys.add(m.group(1))
    return keys


# ----------------------------------------------------------------------------- lint
def all_note_stems():
    return {p.stem for p in WIKI.glob("*.md")}


def link_target(raw):
    # strip display text and heading anchor: [[slug#sec|Display]] -> slug
    raw = raw.replace("\\|", "|")  # escaped pipe used inside markdown tables
    return raw.split("|", 1)[0].split("#", 1)[0].strip()


PLANNED_RE = re.compile(r"^\s*-\s+`([a-z0-9][a-z0-9-]*)`")


def load_planned():
    """Planned-but-unwritten concept slugs, read from map.md's 'Planned concepts'
    section (lines like '- `slug` — description'). Forward-links to these are
    legitimate, not broken."""
    if not MAP.exists():
        return set()
    planned, in_section = set(), False
    for ln in MAP.read_text().split("\n"):
        if ln.startswith("## "):
            in_section = "planned concept" in ln.lower()
            continue
        if in_section:
            m = PLANNED_RE.match(ln)
            if m:
                planned.add(m.group(1))
    return planned


def lint(notes, ref_keys, planned):
    errors, forward = [], []
    stems = all_note_stems() | {"map"}
    for slug, n in notes.items():
        name = n["path"].name
        full = n["path"].read_text()
        for raw in WIKILINK_RE.findall(full):
            tgt = link_target(raw)
            if not tgt or tgt in stems:
                continue
            if tgt in planned:
                forward.append(f"{name}: [[{tgt}]]")
            else:
                errors.append(f"{name}: broken wikilink [[{tgt}]]")
        for req in n["fm"].get("requires", []):
            if req not in notes and req not in planned:
                errors.append(f"{name}: requires unknown note '{req}'")
        for src in n["fm"].get("sources", []):
            if src not in ref_keys:
                errors.append(f"{name}: source key '{src}' missing from references.md")
    return errors, forward


# ----------------------------------------------------------------------------- render
def render_registry(notes):
    rows = []
    for slug in sorted(notes, key=lambda s: notes[s]["fm"].get("title", s).lower()):
        fm = notes[slug]["fm"]
        title = fm.get("title", slug)
        concept = f"[[{slug}\\|{title}]]"
        summary = fm.get("summary", "").replace("|", "\\|")
        tags = " · ".join(fm.get("tags", [])) or "—"
        reqs = fm.get("requires", [])
        requires = " · ".join(f"[[{r}]]" for r in reqs) or "—"
        srcs = fm.get("sources", [])
        src_cells = [(f"{s}{PRIMARY_MARK}" if i == 0 else s) for i, s in enumerate(srcs)]
        sources = " · ".join(src_cells) or "—"
        grade = fm.get("grade", "—")
        reviewed = fm.get("reviewed", "null")
        reviewed = "—" if reviewed in ("null", "", None) else f"{reviewed} ✓"
        rows.append(f"| {concept} | {summary} | {tags} | {requires} | {sources} | {grade} | {reviewed} |")
    header = (
        "| Concept | Summary | Tags | Requires | Sources (" + PRIMARY_MARK + "=derivation-primary) | Grade | Reviewed |\n"
        "|---------|---------|------|----------|--------------------------------|-------|----------|"
    )
    return header + "\n" + "\n".join(rows)


def render_graph(notes):
    lines = ["```mermaid", "graph TD"]
    for slug in sorted(notes):
        for req in notes[slug]["fm"].get("requires", []):
            if req in notes:
                lines.append(f"    {req} --> {slug}")
    # isolated nodes (no prereqs and not required by anyone) still get declared
    referenced = set()
    for slug in notes:
        for req in notes[slug]["fm"].get("requires", []):
            referenced.add(req)
            referenced.add(slug)
    for slug in sorted(notes):
        if slug not in referenced:
            lines.append(f"    {slug}")
    lines.append("```")
    return "\n".join(lines)


def splice(text, name, payload):
    start = f"<!-- autogen:{name}:start -->"
    end = f"<!-- autogen:{name}:end -->"
    if start not in text or end not in text:
        sys.exit(f"ERROR: map.md missing markers for '{name}' ({start} / {end})")
    pre = text.split(start)[0]
    post = text.split(end, 1)[1]
    return f"{pre}{start}\n{payload}\n{end}{post}"


# ----------------------------------------------------------------------------- main
def main():
    check = "--check" in sys.argv
    notes = load_notes()
    ref_keys = load_ref_keys()
    planned = load_planned()

    errors, forward = lint(notes, ref_keys, planned)
    if errors:
        print("LINT FAILED:", file=sys.stderr)
        for e in errors:
            print("  - " + e, file=sys.stderr)
        sys.exit(1)
    if forward:
        print(f"note: {len(forward)} forward-reference(s) to planned (unwritten) notes:")
        for f in forward:
            print("  - " + f)

    if not MAP.exists():
        sys.exit("ERROR: wiki/map.md does not exist (create it with autogen markers first)")

    original = MAP.read_text()
    updated = splice(original, "registry", render_registry(notes))
    updated = splice(updated, "graph", render_graph(notes))

    if check:
        if updated != original:
            sys.exit("map.md is stale: run `python3 scripts/build_index.py` and commit the result")
        print(f"OK: {len(notes)} notes, map.md up to date, lint clean")
        return

    if updated != original:
        MAP.write_text(updated)
        print(f"map.md regenerated ({len(notes)} notes); lint clean")
    else:
        print(f"map.md already current ({len(notes)} notes); lint clean")


if __name__ == "__main__":
    main()
